# Generated by Django 2.2.7 on 2019-11-09 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Families',
            },
        ),
        migrations.CreateModel(
            name='Gardener',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('year_of_birth', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Flower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('color', models.CharField(choices=[('y', 'yellow'), ('r', 'red'), ('g', 'green'), ('b', 'blue'), ('p', 'purple'), ('o', 'orange')], max_length=1)),
                ('description', models.TextField()),
                ('growing_duration', models.PositiveIntegerField(help_text='in Weeks')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yaflod.Family')),
                ('gardener', models.ManyToManyField(to='yaflod.Gardener')),
            ],
        ),
    ]
